# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Klaw_controller
    - Gripper_controller

  Klaw_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  Gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_1
      - gripper_2