# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Klaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    Gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Klaw_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
Gripper_controller:
  ros__parameters:
    joints:
      - gripper_1
      - gripper_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
